FROM public.ecr.aws/bitnami/node:16-prod

ARG NODE_ENV
ARG LOG_LEVEL
ARG PORT
ARG SNAKE_INTERNAL_NAME
ARG MAX_EVALUATION_DEPTH

ENV NODE_ENV=$NODE_ENV
ENV LOG_LEVEL=$LOG_LEVEL
ENV PORT=$PORT
ENV SNAKE_INTERNAL_NAME=$SNAKE_INTERNAL_NAME
ENV MAX_EVALUATION_DEPTH=MAX_EVALUATION_DEPTH

# Bundle app source
COPY node_modules node_modules
COPY build build

EXPOSE $PORT

CMD [ "node", "build/index.js" ]
